[project]
name = "football-fixtures"
version = "0.1.0"
description = "Football fixture planner CLI application"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "typer>=0.15.2",
]
